/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-12-15 07:13:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class winDialog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String CONTEXT_PATH = request.getScheme() + "://"+ request.getServerName() + ":" + request.getServerPort()+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("   <meta http-equiv=\"x-ua-compatible\" content=\"ie=7;ie=8\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(CONTEXT_PATH);
      out.write("dhtmlx/dhtmlx.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(CONTEXT_PATH);
      out.write("dhtmlx/dhtmlx_add.css\" />\r\n");
      out.write("   <script src=\"");
      out.print(CONTEXT_PATH);
      out.write("dhtmlx/dhtmlx.js\"></script>\r\n");
      out.write("   <script language=\"javascript\" src=\"");
      out.print(CONTEXT_PATH);
      out.write("js/ctrl_util.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("      html, body {width:100%; height:100%;overflow:hidden;margin:0px;}\r\n");
      out.write("      body {background-color: transparent;}\r\n");
      out.write("   #back_frame {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   left: 0px;\r\n");
      out.write("   top: 0px;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   display:none;\r\n");
      out.write("}\r\n");
      out.write("   </style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   var title=decodeURI('");
      out.print(request.getParameter("t"));
      out.write("');\r\n");
      out.write("   var urlink='");
      out.print(request.getParameter("l"));
      out.write("';\r\n");
      out.write("   var width='");
      out.print(request.getParameter("w"));
      out.write("';\r\n");
      out.write("   var height='");
      out.print(request.getParameter("h"));
      out.write("';\r\n");
      out.write("   var zIndex;\r\n");
      out.write("   var cw;\r\n");
      out.write("   var dhxWinsGlb;\r\n");
      out.write("   var w;\r\n");
      out.write("   \r\n");
      out.write("   function open(){\r\n");
      out.write("    \tdhxWinsGlb = new dhtmlXWindows();\r\n");
      out.write("//\t   dhxWinsGlb.enableAutoViewport(false);\r\n");
      out.write("\t   dhxWinsGlb.attachViewportTo(\"winvp\");\r\n");
      out.write("//\t   dhxWinsGlb.setImagePath(\"");
      out.print(CONTEXT_PATH);
      out.write("dhtmlx/imgs/\");\r\n");
      out.write("//\t   dhxWinsGlb.setEffect(\"move\", true);\r\n");
      out.write("\t   var mainbody=window.document.body;\r\n");
      out.write("\t   var left=(mainbody.offsetWidth-width)/2;\r\n");
      out.write("\t   var top=(mainbody.offsetHeight-height)/2;\r\n");
      out.write("\r\n");
      out.write("\t  var zi=");
      out.print(request.getParameter("z"));
      out.write(";\r\n");
      out.write("\t  if(zi==null){\r\n");
      out.write("\t\t zIndex=200;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  else {\r\n");
      out.write("\t\t zIndex=zi+200;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  var bf=$$('back_frame');\r\n");
      out.write(" \t  bf.style.zIndex=zIndex;\r\n");
      out.write("\t  w = dhxWinsGlb.createWindow('wn', left,top, width,height);\r\n");
      out.write("     w.setText(title);\r\n");
      out.write("     w.setModal(true);\r\n");
      out.write("     w.button(\"park\").hide();\r\n");
      out.write("     w.attachURL(urlink);\r\n");
      out.write("     w.attachEvent(\"onClose\", doOnCloseWin);\r\n");
      out.write("     w.keepInViewport(true);   \r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function doOnCloseWin(win){\r\n");
      out.write("\t  var fm=w.getFrame().contentWindow.document.forms[0];\r\n");
      out.write("\t  if(typeof(fm)===\"undefined\") {\r\n");
      out.write("\t\t   window.parent.closeWin();\r\n");
      out.write("\t  }\r\n");
      out.write("\t  else {\r\n");
      out.write("\t\t   var dt=formIsDirty(fm);\r\n");
      out.write("\t\t   if(dt){\r\n");
      out.write("\t\t \t  var res=confirm(\"数据已修改，确定要退出？\");\r\n");
      out.write("\t\t \t  if(res){\r\n");
      out.write("\t\t \t\t  window.parent.closeWin();\r\n");
      out.write("\t\t \t  }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    else{\r\n");
      out.write("\t\t\t   window.parent.closeWin();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t  }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function closeWin(){\r\n");
      out.write("\t      var bf=$$('back_frame');\r\n");
      out.write("\t      bf.src='");
      out.print(CONTEXT_PATH);
      out.write("/common/blank.jsp';\r\n");
      out.write(" \t      bf.style.display='none';\r\n");
      out.write("\t      cw=null;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function closedialog(ret) {\r\n");
      out.write("\t   if(ret==false||ret=='false') {\r\n");
      out.write("\t\t  var fm=w.getFrame().contentWindow.document.forms[0];\r\n");
      out.write("\t\t  if(typeof(fm)===\"undefined\") {\r\n");
      out.write("\t\t\t   window.parent.closeWin();\r\n");
      out.write("\t\t\t   return;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t  var dt=formIsDirty(fm);\r\n");
      out.write("\t\t  if(dt){\r\n");
      out.write("\t\t\t  var res=confirm(\"数据已修改，确定要退出？\");\r\n");
      out.write("\t\t\t  if(!res){\r\n");
      out.write("\t\t\t\t  return;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t   }\r\n");
      out.write("\t   \r\n");
      out.write("\t   if(cw==null){\r\n");
      out.write("\t\t   window.parent.closedialog(ret);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   else {\r\n");
      out.write("\t      var bf=$$('back_frame');\r\n");
      out.write("\t      bf.src='");
      out.print(CONTEXT_PATH);
      out.write("/common/blank.jsp';\r\n");
      out.write(" \t      bf.style.display='none';\r\n");
      out.write("\t      cw.closedialog(ret);\r\n");
      out.write("\t      cw=null;\r\n");
      out.write("\t   }\r\n");
      out.write("\t}\r\n");
      out.write("   \r\n");
      out.write("   function closedialog2(ret) {\r\n");
      out.write("\t   if(cw==null){\r\n");
      out.write("\t\t   window.parent.closedialog2(ret);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   else {\r\n");
      out.write("\t      var bf=$$('back_frame');\r\n");
      out.write("\t      bf.src='");
      out.print(CONTEXT_PATH);
      out.write("/common/blank.jsp';\r\n");
      out.write(" \t      bf.style.display='none';\r\n");
      out.write("\t      cw.closedialog2(ret);\r\n");
      out.write("\t      cw=null;\r\n");
      out.write("\t   }\r\n");
      out.write("\t}  \r\n");
      out.write("\r\n");
      out.write("   function openWindow(title,urlink,width,height,pw){\r\n");
      out.write("    \tcw=pw;\r\n");
      out.write(" \t   var bf=$$('back_frame');\r\n");
      out.write(" \t   bf.style.display='block';\r\n");
      out.write(" \t   var ul=escape(urlink);\r\n");
      out.write(" \t   var ln='");
      out.print(CONTEXT_PATH);
      out.write("/common/winDialog.jsp?t='+title+'&l='+ul+'&w='+width+'&h='+height+'&z='+zIndex;\r\n");
      out.write(" \t   bf.src=ln;\r\n");
      out.write("    }\r\n");
      out.write("  </script> \r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"open()\">\r\n");
      out.write("<div id=\"winvp\" style=\"position: relative;height:100%;width:100%;\"></div>\r\n");
      out.write("<iframe id=\"back_frame\" name=\"back_frame\" src=\"");
      out.print(CONTEXT_PATH);
      out.write("/common/blank.jsp\" allowtransparency=\"true\" frameborder=\"0\" scrolling=\"no\"></iframe>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
