/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-12-07 11:28:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

   String path = request.getContextPath();
			String CONTEXT_PATH = request.getScheme() + "://"
					+ request.getServerName() + ":" + request.getServerPort()
					+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tfont-family: 微软雅黑, 宋体, Verdana, Geneva, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#userName {\r\n");
      out.write("    position:absolute;\r\n");
      out.write("\tfont-family: \"微软雅黑\";\r\n");
      out.write("    font-size:18px;\r\n");
      out.write("\tborder: 0px solid #ffffff;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#userName:-webkit-autofill {  \r\n");
      out.write("    -webkit-box-shadow: 0 0 0px 1000px white inset !important;  \r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#password {\r\n");
      out.write("    position:absolute;\r\n");
      out.write(" \tfont-family: \"微软雅黑\";\r\n");
      out.write("    font-size:18px;\r\n");
      out.write("\tborder: 0px solid #ffffff;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#password:-webkit-autofill {  \r\n");
      out.write("    -webkit-box-shadow: 0 0 0px 1000px white inset !important;  \r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#btnSubmit {\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    font-family: \"微软雅黑\";\r\n");
      out.write("    font-size:18px;\r\n");
      out.write("    color:white;\r\n");
      out.write("   \tborder: 1px;\r\n");
      out.write("\tbackground-color:#0132cd;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#imageLogin {\r\n");
      out.write("   position:absolute;\r\n");
      out.write("   top:0px;\r\n");
      out.write("   left:0px;\r\n");
      out.write("   width:100%;\r\n");
      out.write("   height:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">  \r\n");
      out.write("var msg=\"\";\r\n");
      out.write("function checkLength(o,n,min,max) {\r\n");
      out.write("   if(o.value.length > max || o.value.length < min) {\r\n");
      out.write("\t    msg=msg+n+(\"长度必须介于\"+min+\"和\"+max+\"之间。\\r\\n\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t } \r\n");
      out.write("\t else {\r\n");
      out.write("      return true;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkRegexp(o,regexp,n) {\r\n");
      out.write("   if(regexp.test(o.value)) {\r\n");
      out.write("      return true;\r\n");
      out.write("   } \r\n");
      out.write("   else {\r\n");
      out.write("\t    msg=msg+n+\"\\r\\n\";\r\n");
      out.write("      return false;\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkInput(userName,password){\r\n");
      out.write("   var bValid = true;\r\n");
      out.write("\r\n");
      out.write("   bValid = bValid & checkLength(userName,\"用户名\",4,30);\r\n");
      out.write("   //bValid = bValid & checkRegexp(userName,/^[a-z]([0-9a-z_])+$/i,\"用户名必须是字母或数字。\");\r\n");
      out.write("   bValid = bValid & checkLength(password,\"密码\",8,30);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("   return bValid;\r\n");
      out.write("}\r\n");
      out.write("         \r\n");
      out.write("function goValidate(){\r\n");
      out.write("   var uName = document.getElementById(\"userName\");\r\n");
      out.write("   var password =document.getElementById(\"password\");\r\n");
      out.write("   if(checkInput(uName,password)){\r\n");
      out.write("//\t   document.forms[0].action=\"");
      out.print(CONTEXT_PATH);
      out.write("login.do?action=login\";\r\n");
      out.write("\t   document.forms[0].submit();\r\n");
      out.write("   }\r\n");
      out.write("   else {\r\n");
      out.write("      alert(msg);\r\n");
      out.write("      msg=\"\";\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function login(){\r\n");
      out.write("\tvar msg='");
      out.print(request.getAttribute("errMsg"));
      out.write("';\r\n");
      out.write("\tif(msg!='null') alert(msg);\r\n");
      out.write("\tdocument.getElementById(\"userName\").focus();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goKeyPress() {\r\n");
      out.write("\tif(window.event.keyCode == 13) goValidate();  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"login()\">\r\n");
      out.write("<form id=\"loginForm\" action=\"");
      out.print(CONTEXT_PATH);
      out.write("login.do?action=login\" method=\"post\">\r\n");
      out.write("   <img id=\"imageLogin\" src=\"");
      out.print(CONTEXT_PATH);
      out.write("images/login_bg.jpg\" />\r\n");
      out.write("   <input name=\"userName\" id=\"userName\" type=\"text\"  onkeypress=\"goKeyPress()\" value=\"admin\"  maxlength=\"20\" />\r\n");
      out.write("   <input name=\"password\" id=\"password\" type=\"password\"  onkeypress=\"goKeyPress()\" value=\"CHENYANG\" />\r\n");
      out.write("   <input id=\"btnSubmit\" type=\"button\" onclick=\"goValidate()\" onkeypress=\"goKeyPress()\" value=\"登     录\"/>\r\n");
      out.write("</form>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">  \r\n");
      out.write("var iobj=window.document.getElementById('imageLogin');\r\n");
      out.write("var uobj=window.document.getElementById('userName');\r\n");
      out.write("var pobj=window.document.getElementById('password');\r\n");
      out.write("var bobj=window.document.getElementById('btnSubmit');\r\n");
      out.write("\r\n");
      out.write("if(window.addEventListener) {\r\n");
      out.write("     window.addEventListener(\"resize\",goResize,false); \r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("     window.attachEvent('onresize',goResize);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goResize() {\r\n");
      out.write("  if(iobj.offsetWidth<1024) iobj.style.width=\"1024px\";\r\n");
      out.write("  if(iobj.offsetHeight<768) iobj.style.height=\"768px\";\r\n");
      out.write("\r\n");
      out.write("  var he=iobj.offsetHeight;\r\n");
      out.write("  var wd=iobj.offsetWidth;\r\n");
      out.write("  var rtHe=he/760;\r\n");
      out.write("  var rtWd=wd/1440;\r\n");
      out.write("\r\n");
      out.write("  uobj.style.top=parseInt(290*rtHe)+\"px\";\r\n");
      out.write("  pobj.style.top=parseInt(370*rtHe)+\"px\";\r\n");
      out.write("  bobj.style.top=parseInt(440*rtHe)-4+\"px\";\r\n");
      out.write("\r\n");
      out.write("  uobj.style.left=parseInt(925*rtWd)+\"px\";\r\n");
      out.write("  pobj.style.left=parseInt(925*rtWd)+\"px\";\r\n");
      out.write("  bobj.style.left=parseInt(883*rtWd)-1+\"px\";\r\n");
      out.write("\r\n");
      out.write("  uobj.style.width=parseInt(300*rtWd)+\"px\";\r\n");
      out.write("  pobj.style.width=parseInt(300*rtWd)+\"px\";\r\n");
      out.write("  bobj.style.width=parseInt(350*rtWd)+\"px\";\r\n");
      out.write("\r\n");
      out.write("  bobj.style.height=parseInt(44*rtHe)+\"px\";\r\n");
      out.write("}\r\n");
      out.write("goResize();  \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
